// Package main provides the generate command for generating Home Assistant entity constants
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"github.com/Xevion/go-ha/services"

	ha "github.com/Xevion/go-ha"
	"github.com/Xevion/go-ha/types"
	"gopkg.in/yaml.v3"
)

type Config struct {
	URL            string   `yaml:"url"`
	HAAuthToken    string   `yaml:"ha_auth_token"`
	IncludeDomains []string `yaml:"include_domains,omitempty"` // Optional list of domains to include
	ExcludeDomains []string `yaml:"exclude_domains,omitempty"` // Optional list of domains to exclude
}

type Domain struct {
	Name     string
	IDType   string
	Entities []Entity
}

type Entity struct {
	FieldName string
	EntityID  string
}

func toFieldName(entityID string) string {
	parts := strings.Split(entityID, ".")
	if len(parts) != 2 {
		return ""
	}
	return toCamelCase(parts[1])
}

func toCamelCase(s string) string {
	if s == "" {
		return ""
	}

	parts := strings.Split(s, "_")
	var result strings.Builder

	// If first character is numeric
	firstChar := parts[0][0]
	if firstChar >= '0' && firstChar <= '9' {
		result.WriteString("_")
	}

	for _, part := range parts {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(string(part[0])))
		if len(part) > 1 {
			result.WriteString(part[1:])
		}
	}

	return result.String()
}

var entitiesTemplate = template.Must(template.New("entities").Parse(`// Code generated by go generate; DO NOT EDIT.
package entities

{{ if .Domains }}import "github.com/Xevion/go-ha/services"{{ end }}

{{ range .Domains }}
{{- $idType := .IDType }}
type {{ .Name }}Domain struct {
	{{- range .Entities }}
	{{ .FieldName }} services.{{ $idType }}
	{{- end }}
}

var {{ .Name }} = {{ .Name }}Domain{
	{{- range .Entities }}
	{{ .FieldName }}: "{{ .EntityID }}",
	{{- end }}
}
{{ end }}
`))

// includes reports whether a domain survives the include and exclude lists. An
// include list is exclusive: once set, only listed domains pass and the exclude
// list is ignored.
func includes(domain string, include, exclude []string) bool {
	if len(include) > 0 {
		return slices.Contains(include, domain)
	}
	return !slices.Contains(exclude, domain)
}

// render turns a set of entities into the source of the entities package. It is
// separate from generate so the transformation, which produces code users
// compile against, can be tested without a Home Assistant connection.
//
// The output is run through go/format, which both tidies it and rejects any
// result that is not valid Go, so a template or identifier mistake fails here
// rather than in the user's build.
func render(entities []ha.EntityState, include, exclude []string) ([]byte, error) {
	domainMap := make(map[string]*Domain)
	// seen guards against two entity ids camel-casing to the same field, which
	// would emit a struct with a duplicate field and not compile. light.a_b and
	// light.a__b both become AB.
	seen := make(map[string]map[string]string)

	for _, entity := range entities {
		if entity.State == "unavailable" {
			continue
		}

		parts := strings.Split(entity.EntityID, ".")
		if len(parts) != 2 {
			continue
		}
		domain := parts[0]

		if !includes(domain, include, exclude) {
			continue
		}

		field := toFieldName(entity.EntityID)
		if field == "" {
			return nil, fmt.Errorf("entity %q has no usable field name", entity.EntityID)
		}
		if prior, clash := seen[domain][field]; clash {
			return nil, fmt.Errorf("entities %q and %q both map to field %s.%s",
				prior, entity.EntityID, domainName(domain), field)
		}
		if seen[domain] == nil {
			seen[domain] = make(map[string]string)
		}
		seen[domain][field] = entity.EntityID

		if _, exists := domainMap[domain]; !exists {
			// Entities carry their domain's id type, so passing one service
			// another's entity fails to compile.
			idType, ok := services.DomainIDTypes[domain]
			if !ok {
				idType = "EntityID"
			}
			domainMap[domain] = &Domain{Name: domainName(domain), IDType: idType}
		}

		domainMap[domain].Entities = append(domainMap[domain].Entities, Entity{
			FieldName: field,
			EntityID:  entity.EntityID,
		})
	}

	domains := make([]Domain, 0, len(domainMap))
	for _, domain := range domainMap {
		domain.Entities = slices.SortedFunc(slices.Values(domain.Entities), func(a, b Entity) int {
			return strings.Compare(a.FieldName, b.FieldName)
		})
		domains = append(domains, *domain)
	}
	// Map iteration is randomised, so without this the generated file changed
	// byte for byte on every run and showed up in every diff.
	slices.SortFunc(domains, func(a, b Domain) int { return strings.Compare(a.Name, b.Name) })

	var buf bytes.Buffer
	if err := entitiesTemplate.Execute(&buf, struct{ Domains []Domain }{domains}); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated source is not valid Go: %w", err)
	}
	return formatted, nil
}

// domainName is the exported Go identifier for a domain, e.g. input_boolean ->
// InputBoolean.
func domainName(domain string) string { return toCamelCase(domain) }

// generate writes entities/entities.go from the entities the app can see.
func generate(config Config) error {
	app, err := ha.NewApp(types.NewAppRequest{
		URL:         config.URL,
		HAAuthToken: config.HAAuthToken,
	})
	if err != nil {
		return fmt.Errorf("failed to create app: %w", err)
	}
	defer app.Close()

	entities, err := app.State().ListEntities()
	if err != nil {
		return fmt.Errorf("failed to list entities: %w", err)
	}

	out, err := render(entities, config.IncludeDomains, config.ExcludeDomains)
	if err != nil {
		return err
	}

	if err := os.MkdirAll("entities", 0755); err != nil {
		return fmt.Errorf("failed to create entities directory: %w", err)
	}
	if err := os.WriteFile(filepath.Join("entities", "entities.go"), out, 0644); err != nil {
		return fmt.Errorf("failed to write entities.go: %w", err)
	}

	return nil
}

func main() {
	println("Generating entities.go...")
	configFile := flag.String("config", "gen.yaml", "Path to config file")
	flag.Parse()

	absConfigPath, err := filepath.Abs(*configFile)
	if err != nil {
		fmt.Printf("Error resolving config path: %v\n", err)
		os.Exit(1)
	}

	configBytes, err := os.ReadFile(absConfigPath)
	if err != nil {
		fmt.Printf("Error reading config file: %v\n", err)
		os.Exit(1)
	}

	var config Config
	if err := yaml.Unmarshal(configBytes, &config); err != nil {
		fmt.Printf("Error parsing config file: %v\n", err)
		os.Exit(1)
	}

	if config.HAAuthToken == "" {
		config.HAAuthToken = os.Getenv("HA_AUTH_TOKEN")
	}

	if config.URL == "" || config.HAAuthToken == "" {
		fmt.Println("Error: url and ha_auth_token are required in config")
		os.Exit(1)
	}

	if err := generate(config); err != nil {
		fmt.Printf("Error generating entities: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Generated entities/entities.go")
}
